[project]
name = "robotdegilim-xyz-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "boto3>=1.43.83",
    "curl-cffi>=0.16.2",
    "fastapi[standard]>=0.141.1",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
robotdegilim-xyz-backend = "robotdegilim_xyz_backend:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
