from enum import Enum

class S3Prefix(str, Enum):
    """S3 directory prefixes."""
    QUEUE = "queue/"
    JOB_STATES = "job-states/"
    LOCKS = "locks/"

class GlobalLock(str, Enum):
    """Global system lock files."""
    WORKER = "locks/worker.lock"

class JobOutput(str, Enum):
    """Output JSON files generated by jobs."""
    DEPARTMENTS = "departments.json"
    DEPARTMENTS_NO_PREFIX = "departments_noprefix.json"
    DATA = "data.json"
    LAST_UPDATED = "last_updated.json"

class TargetURL(str, Enum):
    """Target URLs for web scraping."""
    OIBS64 = "https://oibs2.metu.edu.tr/View_Program_Course_Details_64/main.php"
    COURSE_CATALOG = "https://catalog.metu.edu.tr/course.php?prog={dept_code}&course_code={course_code}"

DAYS_MAP = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6,
}
