from enum import Enum

class S3Prefix(str, Enum):
    """S3 directory prefixes."""
    QUEUE = "queue/"
    JOB_STATES = "job-states/"
    LOCKS = "locks/"

class GlobalLock(str, Enum):
    """Global system lock files."""
    WORKER = "locks/worker.lock"

class JobOutput(str, Enum):
    """Output JSON files generated by jobs."""
    DEPARTMENTS = "departments.json"
    DEPARTMENTS_NO_PREFIX = "departments_noprefix.json"
    DATA = "data.json"
    LAST_UPDATED = "last_updated.json"

class TargetURL(str, Enum):
    """Target URLs for web scraping."""
    OIBS64 = "https://oibs2.metu.edu.tr/View_Program_Course_Details_64/main.php"
    COURSE_CATALOG = "https://catalog.metu.edu.tr/course.php?prog={dept_code}&course_code={course_code}"

DAYS_MAP = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6,
}

# Manual overrides for specific department codes to bypass fetching prefixes
DEPARTMENT_PREFIX_OVERRIDES = {
    "459": {"n": "Biology Education/Biyoloji Öğretmenliği ", "p": "BED"},
    "422": {"n": "Chemistry Education/Kimya Öğretmenliği ", "p": "CHED"},
    "411": {"n": "Elementary and Early Childhood Education/Temel Eğitim ", "p": "ECE"},
    "410": {"n": "Elementary Education/İlköğretim ", "p": "ELE"},
    "413": {"n": "Elementary Mathematics Educ./İlköğretim Matematik Öğretmenliği ", "p": "EME"},
    "412": {"n": "Elementary Science Education/Fen Bilgisi Öğretmenliği ", "p": "ESE"},
    "423": {"n": "Mathematics Education/Matematik Öğretmenliği ", "p": "MHED"},
    "421": {"n": "Physics Education/Fizik Öğretmenliği ", "p": "PHED"}
}
